
Steps:  
-{
"manifestVersion": 1,
  "id": "xrm-ci-framework-build-tasks",
  "name": "Dynamics 365 Build Tools",
  "version": "9.14.2",
  "publisher": "WaelHamze",
  "targets": [
    {
      "id": "Microsoft.VisualStudio.Services"
    }
  ],
- "description": "Tasks for automating Build & Deployment of Dynamics 365 CE/CDS/PowerApps Solutions",
  "categories": [
    "Build and release"
  ],
  "public": true,
  "galleryFlags": [
    "Preview"
  ],
-  "tags": [
    "Dynamics CRM",
    "CRM",
    "xRM CI Framework",
    "CRM 365",
    "Solution Packager",
    "Package Deployer",
    "Dynamics 365",
    "Customer Engagement",
    "Online Management API",
    "PowerShell",
    "PowerApps",
    "CDS",
    "Flow",
    "Model-Driven PowerApps",
    "Canvas PowerApps"
  ],
 - "icons": {
    "default": "icon_128x128.png"
  },
  "screenshots": [
    {
      "path": "Screenshots/OnlineBuildDefinition.png"
    },
    {
      "path": "Screenshots/OnlineBuildArtifacts.png"
    },
    {
      "path": "Screenshots/ThirdPartyReleaseDefinition.png"
    }
  ],
  "content": {
    "details": {
      "path": "overview.md"
    },
    "license": {
      "path": "license.txt"
    }
  },
  "repository": {
    "type": "git",
    "uri": "https://github.com/WaelHamze/dyn365-ce-vsts-tasks"
  },
  "files": [
    {
      "path": "Images",
      "addressable": true
    },
    {
      "path": "Tasks/MSCRMToolInstaller"
    },
    {
      "path": "Tasks/MSCRMApplySolution"
    },
    {
      "path": "Tasks/MSCRMPing"
    },
    {
      "path": "Tasks/MSCRMPackSolution"
    },
    {
      "path": "Tasks/MSCRMCopySolutionComponents"
    },
    {
      "path": "Tasks/MSCRMRemoveSolution"
    },
    {
      "path": "Tasks/MSCRMRemoveSolutionComponents"
    },
    {
      "path": "Tasks/MSCRMExportSolution"
    },
    {
      "path": "Tasks/MSCRMExtractSolution"
    },
    {
      "path": "Tasks/MSCRMPublishCustomizations"
    },
    {
      "path": "Tasks/MSCRMImportSolution"
    },
    {
      "path": "Tasks/MSCRMPackageDeployer"
    },
    {
      "path": "Tasks/MSCRMUpdateSolutionDescription"
    },
    {
      "path": "Tasks/MSCRMSetVersion"
    },
    {
      "path": "Tasks/MSCRMUpdateSecureConfiguration"
    },
    {
      "path": "Tasks/MSCRMBackupOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMGetOnlineInstanceByName"
    },
    {
      "path": "Tasks/MSCRMPluginRegistration"
    },
    {
      "path": "Tasks/MSCRMProvisionOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMRestoreOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMDeleteOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMSetOnlineInstanceAdminMode"
    },
    {
      "path": "Tasks/MSCRMUpdatePluginAssembly"
    },
    {
      "path": "Tasks/MSCRMUpdateWebResources"
    },
    {
      "path": "Tasks/MSCRMSplitPluginAssembly"
    },
    {
      "path": "Tasks/MSCRMUpdateConfigurationRecords"
    },
    {
      "path": "Tasks/MSCRMServiceEndpointRegistration"
    },
    {
      "path": "Tasks/MSCRMCreateSolution"
    },
    {
      "path": "Tasks/MSCRMCreatePatch"
    },
    {
      "path": "Tasks/MSCRMCloneSolution"
    },
    {
      "path": "Tasks/MSCRMImportSolutionsUsingConfig"
    },
    {
      "path": "Tasks/MSCRMExportSolutionsUsingConfig"
    },
    {
      "path": "Tasks/MSCRMPackSolutionsUsingConfig"
    },
    {
      "path": "Tasks/MSCRMGetSolutionMissingComponents"
    },
    {
      "path": "Tasks/MSCRMGetSolutionMissingDependencies"
    },
    {
      "path": "Tasks/MSCRMResetOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMCopyOnlineInstance"
    },
    {
      "path": "Tasks/MSCRMCheckSolution"
    },
    {
      "path": "Tasks/MSCRMGetSolution"
    },
    {
      "path": "Tasks/MSCRMGetLatestPatch"
    },
    {
      "path": "Tasks/MSCRMExportCMData"
    },
    {
      "path": "Tasks/MSCRMImportCMData"
    },
    {
      "path": "Tasks/MSCRMExtractCMData"
    },
    {
      "path": "Tasks/MSCRMPackCMData"
    },
    {
      "path": "Tasks/MSCRMGetConfigurationRecord"
    },
    {
      "path": "Tasks/MSCRMGetEnvironmentVariable"
    },
    {
      "path": "Tasks/MSCRMUpdateEnvironmentVariables"
    },
    {
      "path": "Tasks/MSCRMCheckerQualityGate"
    }
  ],
  "contributions": [
    {
      "id": "MSCRMToolInstaller",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMToolInstaller"
      }
    },
    {
      "id": "MSCRMApplySolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMApplySolution"
      }
    },
    {
      "id": "MSCRMPing",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPing"
      }
    },
    {
      "id": "MSCRMPackSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPackSolution"
      }
    },
    {
      "id": "MSCRMExportSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMExportSolution"
      }
    },
    {
      "id": "MSCRMExtractSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMExtractSolution"
      }
    },
    {
      "id": "MSCRMPublishCustomizations",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPublishCustomizations"
      }
    },
    {
      "id": "MSCRMImportSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMImportSolution"
      }
    },
    {
      "id": "MSCRMPackageDeployer",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPackageDeployer"
      }
    },
    {
      "id": "MSCRMSetVersion",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMSetVersion"
      }
    },
    {
      "id": "MSCRMUpdateSolutionDescription",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdateSolutionDescription"
      }
    },
    {
      "id": "MSCRMCopySolutionComponents",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCopySolutionComponents"
      }
    },
    {
      "id": "MSCRMRemoveSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMRemoveSolution"
      }
    },
    {
      "id": "MSCRMRemoveSolutionComponents",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMRemoveSolutionComponents"
      }
    },
    {
      "id": "MSCRMUpdateSecureConfiguration",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdateSecureConfiguration"
      }
    },
    {
      "id": "MSCRMBackupOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMBackupOnlineInstance"
      }
    },
    {
      "id": "MSCRMGetOnlineInstanceByName",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetOnlineInstanceByName"
      }
    },
    {
      "id": "MSCRMPluginRegistration",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPluginRegistration"
      }
    },
    {
      "id": "MSCRMProvisionOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMProvisionOnlineInstance"
      }
    },
    {
      "id": "MSCRMRestoreOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMRestoreOnlineInstance"
      }
    },
    {
      "id": "MSCRMDeleteOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMDeleteOnlineInstance"
      }
    },
    {
      "id": "MSCRMSetOnlineInstanceAdminMode",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMSetOnlineInstanceAdminMode"
      }
    },
    {
      "id": "MSCRMUpdatePluginAssembly",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdatePluginAssembly"
      }
    },
    {
      "id": "MSCRMUpdateWebResources",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdateWebResources"
      }
    },
    {
      "id": "MSCRMSplitPluginAssembly",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMSplitPluginAssembly"
      }
    },
    {
      "id": "MSCRMUpdateConfigurationRecords",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdateConfigurationRecords"
      }
    },
    {
      "id": "MSCRMServiceEndpointRegistration",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMServiceEndpointRegistration"
      }
    },
    {
      "id": "MSCRMCreateSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCreateSolution"
      }
    },
    {
      "id": "MSCRMCreatePatch",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCreatePatch"
      }
    },
    {
      "id": "MSCRMCloneSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCloneSolution"
      }
    },
    {
      "id": "MSCRMExportSolutionsUsingConfig",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMExportSolutionsUsingConfig"
      }
    },
    {
      "id": "MSCRMImportSolutionsUsingConfig",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMImportSolutionsUsingConfig"
      }
    },
    {
      "id": "MSCRMPackSolutionsUsingConfig",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPackSolutionsUsingConfig"
      }
    },
    {
      "id": "MSCRMGetSolutionMissingComponents",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetSolutionMissingComponents"
      }
    },
    {
      "id": "MSCRMGetSolutionMissingDependencies",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetSolutionMissingDependencies"
      }
    },
    {
      "id": "MSCRMResetOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMResetOnlineInstance"
      }
    },
    {
      "id": "MSCRMCopyOnlineInstance",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCopyOnlineInstance"
      }
    },
    {
      "id": "MSCRMCheckSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCheckSolution"
      }
    },
    {
      "id": "MSCRMGetSolution",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetSolution"
      }
    },
    {
      "id": "MSCRMGetLatestPatch",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetLatestPatch"
      }
    },
    {
      "id": "MSCRMExportCMData",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMExportCMData"
      }
    },
    {
      "id": "MSCRMImportCMData",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMImportCMData"
      }
    },
    {
      "id": "MSCRMExtractCMData",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMExtractCMData"
      }
    },
    {
      "id": "MSCRMPackCMData",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMPackCMData"
      }
    },
    {
      "id": "MSCRMGetConfigurationRecord",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetConfigurationRecord"
      }
    },
    {
      "id": "MSCRMGetEnvironmentVariable",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMGetEnvironmentVariable"
      }
    },
    {
      "id": "MSCRMUpdateEnvironmentVariables",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMUpdateEnvironmentVariables"
      }
    },
    {
      "id": "MSCRMCheckerQualityGate",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "Tasks/MSCRMCheckerQualityGate"
      }
    }
  ]
}

